# Generated by Django 2.2.5 on 2020-05-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200520_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='contry',
            new_name='country',
        ),
    ]
