# Generated by Django 2.2.5 on 2020-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200524_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.CharField(default='37.2429359', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.CharField(default='131.8580873', max_length=20),
        ),
    ]
